-- Phase 7.5: the Lessons module's lessons, written in the app as ordered Markdown sections, and
-- the user's activity on them: each time they open a lesson (its latest is when it was last
-- reviewed) and each progress they report (the latest is its progress). Both are kept per
-- user. Deleting a lesson deletes its sections and activity.

create table lessons (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(200) not null,
    summary text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint lessons_user_id_fk foreign key (user_id) references users (id)
);

create table lesson_sections (
    lesson_id bigint not null,
    position integer not null,
    title varchar(200) not null,
    body text not null,
    primary key (lesson_id, position),
    constraint lesson_sections_position_check check (position >= 0),
    constraint lesson_sections_lesson_id_fk foreign key (lesson_id) references lessons (id) on delete cascade
);

create table lesson_opens (
    id bigint generated by default as identity primary key,
    lesson_id bigint not null,
    user_id bigint not null,
    opened_at timestamp(6) with time zone not null,
    constraint lesson_opens_lesson_id_fk foreign key (lesson_id) references lessons (id) on delete cascade,
    constraint lesson_opens_user_id_fk foreign key (user_id) references users (id)
);

create index lesson_opens_lesson_id_idx on lesson_opens (lesson_id);

create table lesson_progress_updates (
    id bigint generated by default as identity primary key,
    lesson_id bigint not null,
    user_id bigint not null,
    recorded_at timestamp(6) with time zone not null,
    progress integer not null,
    constraint lesson_progress_updates_progress_range check (progress between 0 and 100),
    constraint lesson_progress_updates_lesson_id_fk foreign key (lesson_id) references lessons (id)
        on delete cascade,
    constraint lesson_progress_updates_user_id_fk foreign key (user_id) references users (id)
);

create index lesson_progress_updates_lesson_id_idx on lesson_progress_updates (lesson_id);

-- A node can list a lesson as a resource, by plain id in target_id like a deck or material.
alter table node_resources drop constraint node_resources_resource_type_check;
alter table node_resources add constraint node_resources_resource_type_check
    check (resource_type in ('url', 'tree', 'deck', 'material', 'lesson'));

alter table node_resources drop constraint node_resources_target_matches_type;
alter table node_resources add constraint node_resources_target_matches_type check (
    (resource_type = 'url' and url is not null and tree_id is null and target_id is null)
    or (resource_type = 'tree' and tree_id is not null and url is null and target_id is null)
    or (resource_type in ('deck', 'material', 'lesson') and target_id is not null and url is null
        and tree_id is null));
