-- Phase 7.6: the Coding practice module. Questions are written problems the user solves on
-- their own machine, grouped into sets. Each question has a problem statement, worked
-- examples and a solution kept hidden until the user asks to see it. The user's attempts
-- are kept per user: revealing the solution, and marking the question solved. A question
-- is solved once marked so; a set's readiness is the share of its questions solved.
-- Languages start with HTML and CSS; JavaScript comes later by widening the check.

create table question_sets (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(200) not null,
    description text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint question_sets_user_id_fk foreign key (user_id) references users (id)
);

create table coding_questions (
    id bigint generated by default as identity primary key,
    set_id bigint not null,
    title varchar(200) not null,
    language varchar(20) not null,
    problem text not null,
    examples text,
    solution text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint coding_questions_language_check check (language in ('html', 'css')),
    constraint coding_questions_set_id_fk foreign key (set_id) references question_sets (id) on delete cascade
);

create index coding_questions_set_id_idx on coding_questions (set_id);

create table question_attempts (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    user_id bigint not null,
    recorded_at timestamp(6) with time zone not null,
    action varchar(20) not null,
    constraint question_attempts_action_check check (action in ('revealed', 'solved')),
    constraint question_attempts_question_id_fk foreign key (question_id) references coding_questions (id)
        on delete cascade,
    constraint question_attempts_user_id_fk foreign key (user_id) references users (id)
);

create index question_attempts_question_id_idx on question_attempts (question_id);

-- A node can list a question set as a resource, by plain id in target_id.
alter table node_resources drop constraint node_resources_resource_type_check;
alter table node_resources add constraint node_resources_resource_type_check
    check (resource_type in ('url', 'tree', 'deck', 'material', 'lesson', 'question_set'));

alter table node_resources drop constraint node_resources_target_matches_type;
alter table node_resources add constraint node_resources_target_matches_type check (
    (resource_type = 'url' and url is not null and tree_id is null and target_id is null)
    or (resource_type = 'tree' and tree_id is not null and url is null and target_id is null)
    or (resource_type in ('deck', 'material', 'lesson', 'question_set') and target_id is not null
        and url is null and tree_id is null));
