-- The Milestone 1 schema, exactly as Hibernate's ddl-auto=update built it (exported from
-- Postgres with pg_dump and tidied). Databases that already had these tables are baselined
-- at this version instead of running it; see spring.flyway.baseline-on-migrate.
-- The generated constraint names (fk..., uk...) are replaced with readable ones in V2.

create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    username varchar(100) not null,
    constraint ukr43af9ap4edm43mmtq01oddj6 unique (username)
);

create table nodes (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    description text,
    readiness integer not null,
    readiness_source_type varchar(50) not null,
    title varchar(200) not null,
    updated_at timestamp(6) with time zone not null,
    user_id bigint not null,
    constraint nodes_readiness_range check (readiness >= 0 and readiness <= 100),
    constraint nodes_readiness_source_type_check check (readiness_source_type = 'manual'),
    constraint fkt67ih9ta1epitin6upf11sh27 foreign key (user_id) references users (id)
);

create table node_links (
    node_id bigint not null,
    label varchar(200),
    url varchar(2048) not null,
    position integer not null,
    primary key (node_id, position),
    constraint node_links_position_check check (position >= 0),
    constraint fkitb245un9qusy9w2tsiemv6ts foreign key (node_id) references nodes (id)
);

create table trees (
    id bigint generated by default as identity primary key,
    category varchar(100),
    created_at timestamp(6) with time zone not null,
    description text,
    title varchar(200) not null,
    updated_at timestamp(6) with time zone not null,
    user_id bigint not null,
    constraint fk492i19ei0gikgxgcj00bflhs1 foreign key (user_id) references users (id)
);

create table tree_tags (
    tree_id bigint not null,
    tag varchar(50) not null,
    position integer not null,
    primary key (tree_id, position),
    constraint tree_tags_position_check check (position >= 0),
    constraint fk3t042ytiooba6r04w5i34hmpb foreign key (tree_id) references trees (id)
);

create table tree_nodes (
    id bigint generated by default as identity primary key,
    aggregate_threshold integer not null,
    individual_threshold integer not null,
    position_x double precision not null,
    position_y double precision not null,
    node_id bigint not null,
    tree_id bigint not null,
    constraint tree_nodes_aggregate_threshold_range check (aggregate_threshold >= 0 and aggregate_threshold <= 100),
    constraint tree_nodes_individual_threshold_range check (individual_threshold >= 0 and individual_threshold <= 100),
    constraint tree_nodes_tree_node_unique unique (tree_id, node_id),
    constraint fkhoi18dkkpcx3nadic3spfpkcj foreign key (tree_id) references trees (id) on delete cascade,
    constraint fkqblynt4o8gnu7rr3vivcwv8rn foreign key (node_id) references nodes (id)
);

create table prerequisites (
    id bigint generated by default as identity primary key,
    dependent_tree_node_id bigint not null,
    prerequisite_tree_node_id bigint not null,
    constraint prerequisites_no_self_edge check (prerequisite_tree_node_id <> dependent_tree_node_id),
    constraint prerequisites_edge_unique unique (prerequisite_tree_node_id, dependent_tree_node_id),
    constraint fkcfutkrxa5alu4s5nib4jg3eip foreign key (dependent_tree_node_id) references tree_nodes (id) on delete cascade,
    constraint fkker9yasa0wtiukrw3awfp0oh2 foreign key (prerequisite_tree_node_id) references tree_nodes (id) on delete cascade
);
