-- Phase 5.3a: tags on library nodes, and the restore point taken when a tree enters edit mode.

create table node_tags (
    node_id bigint not null,
    tag varchar(50) not null,
    position integer not null,
    primary key (node_id, position),
    constraint node_tags_position_check check (position >= 0),
    constraint node_tags_node_id_fk foreign key (node_id) references nodes (id)
);

-- At most one edit session per tree. snapshot is JSON (TreeSnapshot): the tree's details,
-- placements, thresholds and edges when "Edit" was clicked. It's only read by the app, so
-- plain text is enough.
create table tree_edit_sessions (
    id bigint generated by default as identity primary key,
    tree_id bigint not null,
    started_at timestamp(6) with time zone not null,
    snapshot text not null,
    constraint tree_edit_sessions_tree_id_unique unique (tree_id),
    constraint tree_edit_sessions_tree_id_fk foreign key (tree_id) references trees (id) on delete cascade
);
