-- Phase 7.1: the Flashcards module's decks, cards and card reviews. Deleting a deck deletes
-- its cards, and deleting a card deletes its reviews.

create table decks (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(200) not null,
    description text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint decks_user_id_fk foreign key (user_id) references users (id)
);

create table cards (
    id bigint generated by default as identity primary key,
    deck_id bigint not null,
    front text not null,
    back text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint cards_deck_id_fk foreign key (deck_id) references decks (id) on delete cascade
);

-- One row per answer: who answered, when, and whether they got it right. A card has passed
-- when its user's last three answers were all correct (see CardProgress).
create table card_reviews (
    id bigint generated by default as identity primary key,
    card_id bigint not null,
    user_id bigint not null,
    reviewed_at timestamp(6) with time zone not null,
    correct boolean not null,
    constraint card_reviews_card_id_fk foreign key (card_id) references cards (id) on delete cascade,
    constraint card_reviews_user_id_fk foreign key (user_id) references users (id)
);

-- Cards are read by deck, and reviews by card
create index cards_deck_id_idx on cards (deck_id);
create index card_reviews_card_id_idx on card_reviews (card_id);
