-- Phase 7.4: the Materials module's external materials (an article, a video, a course: a URL
-- with a title and notes) and the progress the user reports on them. Every progress update is
-- kept; the latest is the material's current progress, and its time is when the material
-- was last reviewed. Deleting a material deletes its updates.

create table materials (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(200) not null,
    url varchar(2048) not null,
    notes text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint materials_user_id_fk foreign key (user_id) references users (id)
);

create table material_progress_updates (
    id bigint generated by default as identity primary key,
    material_id bigint not null,
    user_id bigint not null,
    recorded_at timestamp(6) with time zone not null,
    progress integer not null,
    note text,
    constraint material_progress_updates_progress_range check (progress between 0 and 100),
    constraint material_progress_updates_material_id_fk foreign key (material_id) references materials (id)
        on delete cascade,
    constraint material_progress_updates_user_id_fk foreign key (user_id) references users (id)
);

create index material_progress_updates_material_id_idx on material_progress_updates (material_id);

-- A node can list a material as a resource, by plain id in target_id like a deck.
alter table node_resources drop constraint node_resources_resource_type_check;
alter table node_resources add constraint node_resources_resource_type_check
    check (resource_type in ('url', 'tree', 'deck', 'material'));

alter table node_resources drop constraint node_resources_target_matches_type;
alter table node_resources add constraint node_resources_target_matches_type check (
    (resource_type = 'url' and url is not null and tree_id is null and target_id is null)
    or (resource_type = 'tree' and tree_id is not null and url is null and target_id is null)
    or (resource_type in ('deck', 'material') and target_id is not null and url is null and tree_id is null));
